/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.*;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rajat Mishra
 */
public class screen_3 extends javax.swing.JFrame {
private DisplayManager mgr;
public screen_3(DisplayManager mgr) {
        this.mgr = mgr;
        initComponents();
        setIcon();
    }
    /**
     * Creates new form screen_3
     */
    public screen_3() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PassengerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ProceedButton = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Fields = new javax.swing.JLabel();
        Via = new javax.swing.JLabel();
        Flight = new javax.swing.JLabel();
        Arrival = new javax.swing.JLabel();
        Departure = new javax.swing.JLabel();
        Transit = new javax.swing.JLabel();
        TotalDuration = new javax.swing.JLabel();
        FromViaTo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Passenger Details");
        setBounds(new java.awt.Rectangle(500, 150, 700, 600));
        setMinimumSize(new java.awt.Dimension(960, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        PassengerName.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        PassengerName.setForeground(new java.awt.Color(255, 255, 255));
        PassengerName.setOpaque(false);
        getContentPane().add(PassengerName);
        PassengerName.setBounds(445, 305, 387, 60);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setText("PASSENGER NAME :");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 300, 390, 60);

        jLabel3.setBackground(new java.awt.Color(202, 11, 23));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PASSENGER DETAILS");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 960, 70);

        ProceedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Proceedbuttondefault.png"))); // NOI18N
        ProceedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProceedButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProceedButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProceedButtonMouseExited(evt);
            }
        });
        getContentPane().add(ProceedButton);
        ProceedButton.setBounds(670, 590, 160, 50);

        jPanel1.setBackground(new java.awt.Color(202, 11, 23));
        jPanel1.setLayout(null);

        Fields.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Fields.setForeground(new java.awt.Color(153, 153, 153));
        Fields.setText("   VIA                          FLIGHT                        DEPARTURE                             ARRIVAL                      TRANSIT TIME        TOTAL DURATION");
        jPanel1.add(Fields);
        Fields.setBounds(0, 0, 960, 30);

        Via.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Via.setForeground(new java.awt.Color(255, 255, 255));
        Via.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(Via);
        Via.setBounds(0, 40, 80, 80);

        Flight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Flight.setForeground(new java.awt.Color(255, 255, 255));
        Flight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Flight);
        Flight.setBounds(90, 40, 170, 80);

        Arrival.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Arrival.setForeground(new java.awt.Color(255, 255, 255));
        Arrival.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Arrival);
        Arrival.setBounds(450, 40, 190, 80);

        Departure.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Departure.setForeground(new java.awt.Color(255, 255, 255));
        Departure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Departure);
        Departure.setBounds(260, 40, 190, 80);

        Transit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Transit.setForeground(new java.awt.Color(255, 255, 255));
        Transit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Transit);
        Transit.setBounds(650, 40, 140, 80);

        TotalDuration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TotalDuration.setForeground(new java.awt.Color(255, 255, 255));
        TotalDuration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(TotalDuration);
        TotalDuration.setBounds(790, 40, 170, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 140, 960, 120);

        FromViaTo.setBackground(new java.awt.Color(255, 255, 153));
        FromViaTo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        FromViaTo.setForeground(new java.awt.Color(153, 0, 51));
        FromViaTo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(FromViaTo);
        FromViaTo.setBounds(0, 70, 960, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/airplane-wallpaper-for-desktop.jpg"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(733, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 70, 960, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProceedButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProceedButtonMouseEntered
        ImageIcon search1 = new ImageIcon(getClass().getResource("/Images/Proceedbuttonover.png"));
        ProceedButton.setIcon(search1);
    }//GEN-LAST:event_ProceedButtonMouseEntered

    private void ProceedButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProceedButtonMouseExited
           ImageIcon search1 = new ImageIcon(getClass().getResource("/Images/Proceedbuttondefault.png"));
        ProceedButton.setIcon(search1);
    }//GEN-LAST:event_ProceedButtonMouseExited

    private void ProceedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProceedButtonMouseClicked
       if(PassengerName.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "No Name Provided\n;-)", "Information", JOptionPane.INFORMATION_MESSAGE);
       }
       else
       {
           mgr.mgr.displayMgr.showScreen4();
       }
        
    }//GEN-LAST:event_ProceedButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Arrival;
    public javax.swing.JLabel Departure;
    private javax.swing.JLabel Fields;
    public javax.swing.JLabel Flight;
    public javax.swing.JLabel FromViaTo;
    public javax.swing.JTextField PassengerName;
    private javax.swing.JLabel ProceedButton;
    public javax.swing.JLabel TotalDuration;
    public javax.swing.JLabel Transit;
    public javax.swing.JLabel Via;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Icon.png")));
    }
}
