/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Rajat Mishra
 */
import AppPackage.AnimationClass;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
public class screen_1 extends javax.swing.JFrame {

   private DisplayManager mgr;  /**
     * Creates new form screen_1
     */
 public screen_1(DisplayManager mgr) {
        this.mgr = mgr;
        initComponents();
        SlideShow();
        setIcon();
    }
    private AnimationClass ac = new AnimationClass();

    public screen_1() { 
        initComponents();
        SlideShow();
       setIcon();
    }

    public void SlideShow() {
        new Thread() {
            int count;

            @Override
            public void run() {
                try {
                    while (true) {
                        switch (count) {
                            case 0:
                               ImageIcon ii = new ImageIcon(getClass().getResource("/Images/sl1.jpg"));
                                Backslide1.setIcon(ii);
                                Thread.sleep(4000);
                                ac.jLabelXLeft(0, -660, 20, 6, Backslide1);
                                ac.jLabelXLeft(660, 0, 20, 6, Backslide2);
                                count = 1;
                                break;
                            case 1:
                                ImageIcon ii1 = new ImageIcon(getClass().getResource("/Images/aero.jpg"));
                                Backslide2.setIcon(ii1);
                                Thread.sleep(4000);
                                ac.jLabelXRight(0, 660, 20, 6, Backslide2);
                                ac.jLabelXRight(-660, 0, 20, 6, Backslide1);

                                count = 2;
                                break;

                            case 2:
                                ImageIcon ii2 = new ImageIcon(getClass().getResource("/Images/aeroplane-with-people-on-the-sky-640x480.jpg"));
                                Backslide1.setIcon(ii2);

                                Thread.sleep(4000);
                                ac.jLabelXLeft(0, -660, 20, 6, Backslide1);
                                ac.jLabelXLeft(660, 0, 20, 6, Backslide2);

                                count = 3;
                                break;
                            case 3:
                                ImageIcon ii3 = new ImageIcon(getClass().getResource("/Images/Wallpapersxl Aeroplanes Pin Airplanes Airplane Sunset Scenery On Pinterest 133796 1366x768.jpg"));
                                Backslide2.setIcon(ii3);
                                Thread.sleep(4000);
                                ac.jLabelXRight(0, 660, 20, 6, Backslide2);
                                ac.jLabelXRight(-660, 0, 20, 6, Backslide1);

                                count = 4;
                                break;
                            case 4:
                                ImageIcon ii4 = new ImageIcon(getClass().getResource("/Images/slide2.jpg"));
                                Backslide1.setIcon(ii4);
                                Thread.sleep(4000);
                                ac.jLabelXRight(0, 660, 20, 6, Backslide2);
                                ac.jLabelXRight(-660, 0, 20, 6, Backslide1);

                                count = 0;
                                break;

                        }
                    }
                } catch (Exception e) {

                }
            }
        }.start();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Backslide1 = new javax.swing.JLabel();
        Backslide2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        From = new javax.swing.JComboBox<>();
        To = new javax.swing.JComboBox<>();
        Passenger = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JLabel();
        Date = new datechooser.beans.DateChooserCombo();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Ticket");
        setBackground(new java.awt.Color(255, 51, 51));
        setBounds(new java.awt.Rectangle(600, 100, 660, 760));
        setMinimumSize(new java.awt.Dimension(660, 760));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(202, 11, 23));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOK FLIGHT");
        jLabel1.setMinimumSize(new java.awt.Dimension(660, 450));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 0, 410, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/download.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 120, 110);

        Backslide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sl1.jpg"))); // NOI18N
        Backslide1.setPreferredSize(new java.awt.Dimension(660, 300));
        getContentPane().add(Backslide1);
        Backslide1.setBounds(0, 110, 660, 340);

        Backslide2.setText("jLabel5");
        getContentPane().add(Backslide2);
        Backslide2.setBounds(660, 110, 660, 340);

        jPanel1.setBackground(new java.awt.Color(202, 11, 23));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(null);

        From.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        From.setForeground(new java.awt.Color(255, 102, 102));
        From.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "DELHI", "MUMBAI", "PUNE" }));
        From.setToolTipText("From");
        From.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(From);
        From.setBounds(60, 40, 190, 30);

        To.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        To.setForeground(new java.awt.Color(255, 102, 102));
        To.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SINGAPORE" }));
        To.setToolTipText("To");
        To.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(To);
        To.setBounds(360, 40, 190, 30);

        Passenger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Passenger.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        Passenger.setToolTipText("Number Of Passenger");
        jPanel2.add(Passenger);
        Passenger.setBounds(360, 130, 70, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FROM");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 10, 190, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TO");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(360, 10, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATE");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(60, 100, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PASSENGER");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(360, 100, 110, 30);

        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_def.png"))); // NOI18N
        SearchButton.setText("jLabel4");
        SearchButton.setToolTipText("Search");
        SearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchButtonMousePressed(evt);
            }
        });
        jPanel2.add(SearchButton);
        SearchButton.setBounds(420, 180, 184, 55);

        Date.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    Date.setCalendarBackground(new java.awt.Color(255, 153, 153));
    Date.setCalendarPreferredSize(new java.awt.Dimension(200, 160));
    Date.setNothingAllowed(false);
    Date.setFormat(2);
    try {
        Date.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2016, 9, 1),
            new java.util.GregorianCalendar(2016, 9, 1))));
} catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
    e1.printStackTrace();
    }
    Date.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 16));
    Date.setMaxDate(new java.util.GregorianCalendar(2016, 10, 14));
    Date.setMinDate(new java.util.GregorianCalendar(2016, 9, 1));
    Date.setCurrentNavigateIndex(0);
    Date.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
    jPanel2.add(Date);
    Date.setBounds(60, 130, 190, 30);

    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow.png"))); // NOI18N
    jPanel2.add(jLabel4);
    jLabel4.setBounds(290, 40, 30, 30);

    jPanel1.add(jPanel2);
    jPanel2.setBounds(20, 10, 620, 250);

    getContentPane().add(jPanel1);
    jPanel1.setBounds(0, 450, 660, 330);

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/download 2.jpg"))); // NOI18N
    getContentPane().add(jLabel2);
    jLabel2.setBounds(530, 0, 130, 110);

    pack();
    }// </editor-fold>//GEN-END:initComponents
private void ToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToActionPerformed

    private void SearchButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseReleased
        // TODO add your handling code here:
        ImageIcon search1 = new ImageIcon(getClass().getResource("/Images/button_def.png"));
        SearchButton.setIcon(search1);
    }//GEN-LAST:event_SearchButtonMouseReleased

    private void SearchButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonMousePressed

    private void SearchButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseExited
        // TODO add your handling code here:
        ImageIcon search1 = new ImageIcon(getClass().getResource("/Images/button_def.png"));
        SearchButton.setIcon(search1);
    }//GEN-LAST:event_SearchButtonMouseExited

    private void SearchButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseEntered
        // TODO add your handling code here:
        ImageIcon search1 = new ImageIcon(getClass().getResource("/Images/button_mouse_over.png"));
        SearchButton.setIcon(search1);
    }//GEN-LAST:event_SearchButtonMouseEntered

    private void SearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchButtonMouseClicked

        if (From.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "No field Should be empty\n;-)", "Information", JOptionPane.INFORMATION_MESSAGE);
            
        }
        else {
            try {
                String Origin=this.From.getSelectedItem().toString();
                String p=this.Passenger.getValue().toString();
                int PassengerNo=Integer.parseInt(p);
                String  date = this.Date.getSelection().toString();
                //System.out.println(date);
                date= date.substring(1, date.length()-1);
                String[] values = date.split(" ");
                String monthdate = String.format("%02d", Integer.parseInt(values[0]));
                String month = values[1].substring(0, 3).toUpperCase();
                String year = values[2].substring(2);
                String concatdate = monthdate+" "+month+" "+year;
                this.setVisible(false); 
                mgr.showScreen2(PassengerNo,Origin,concatdate);
            } catch (ParseException ex) {
                System.out.println("Rajat");
            } catch (IOException ex) {
                System.out.println("Mishra");
            }
           }
    }//GEN-LAST:event_SearchButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backslide1;
    private javax.swing.JLabel Backslide2;
    public datechooser.beans.DateChooserCombo Date;
    public javax.swing.JComboBox<String> From;
    public javax.swing.JSpinner Passenger;
    public javax.swing.JLabel SearchButton;
    public javax.swing.JComboBox<String> To;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/Icon.png")));
    }
}